name: Build and publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main" # deploy from main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook
      
      - name: Deploy to GitHub Pages
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: dist/storybook
