name: Build and publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main" # deploy from main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
